name: Continuous Integration with Github Actions
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DATABASE: ${{ secrets.DATABASE }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - uses: actions/checkout@v4
      - name: Deploy app
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build Application Jar
        run: mvn clean package -DskipTests

      - name: Push to Docker Hub Container registry
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/hotel-california:latest
          docker tag  ${{ secrets.DOCKER_USERNAME }}/hotel-california:latest ${{ secrets.DOCKER_USERNAME }}/hotel-california:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/hotel-california:${{github.run_id}} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hotel-california:latest

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
