# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Continuous Integration with Github Actions

on:
  push:
    branches:  
    - master 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/setup-java@v4
    - name: Set up JDK 17
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application.jar
      run: mvn clean package -DskipTests
      

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/api-hotel-california:latest

    - name: Push the Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/api-hotel-california:latest
    
    - name: Docker Compose Build 
      run: docker compose up --build

